/*
 * Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE
 * file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file
 * to You under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the
 * License. You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package org.palading.clivia.dbCore.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@Entity
@Table(name = "tbl_api_info")
public class TblApiInfo {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_api_info.api_id
     *
     *
     */
    @Id
    @Column(name = "api_id")
    private String apiId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_api_info.api_name
     *
     *
     */
    @Column(name = "api_name")
    private String apiName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_api_info.app_id
     *
     *
     */
    @Column(name = "app_id")
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_api_info.group_id
     *
     *
     */
    @Column(name = "group_id")
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_api_info.rpc_type
     *
     *
     */
    @Column(name = "rpc_type")
    private String rpcType;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_api_info.version
     *
     *
     */
    @Column(name = "version")
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_api_info.api_type
     *
     *
     */
    @Column(name = "api_type")
    private String apiType;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_api_info.enabled
     *
     *
     */
    @Column(name = "api_enabled")
    private String apiEnabled;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_api_info.api_header
     *
     *
     */
    @Column(name = "api_header")
    private String apiHeader;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_api_info.api_rewrite
     *
     *
     */
    @Column(name = "api_rewrite")
    private String apiRewrite;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_api_info.url
     *
     *
     */
    @Column(name = "url")
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_api_info.method_type
     *
     *
     */
    @Column(name = "method_type")
    private String methodType;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_api_info.api_req_size
     *
     *
     */
    @Column(name = "api_req_size")
    private String apiReqSize;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_api_info.blackListEnabled
     *
     *
     */
    @Column(name = "black_list_enabled")
    private String blacklistEnabled;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_api_info.api_hystrix
     *
     *
     */
    @Column(name = "api_hystrix")
    private String apiHystrix;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_api_info.api_request_limit
     *
     *
     */
    @Column(name = "api_request_limit")
    private String apiRequestLimit;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_api_info.api_http_route
     *
     *
     */
    @Column(name = "api_http_route")
    private String apiHttpRoute;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_api_info.api_auth
     *
     *
     */
    @Column(name = "api_auth")
    private String apiAuth;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_api_info.create_user
     *
     *
     */
    @Column(name = "create_user")
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_api_info.create_time
     *
     *
     */
    @Column(name = "create_time")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_api_info.update_user
     *
     *
     */
    @Column(name = "update_user")
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_api_info.update_time
     *
     *
     */
    @Column(name = "update_time")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_api_info.api_non_httpRoute
     *
     *
     */
    @Column(name = "api_non_http_route")
    private String apiNonHttproute;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_api_info.api_id
     *
     * @return the value of tbl_api_info.api_id
     *
     *
     */
    public String getApiId() {
        return apiId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_api_info.api_id
     *
     * @param apiId
     *            the value for tbl_api_info.api_id
     *
     *
     */
    public void setApiId(String apiId) {
        this.apiId = apiId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_api_info.api_name
     *
     * @return the value of tbl_api_info.api_name
     *
     *
     */
    public String getApiName() {
        return apiName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_api_info.api_name
     *
     * @param apiName
     *            the value for tbl_api_info.api_name
     *
     *
     */
    public void setApiName(String apiName) {
        this.apiName = apiName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_api_info.app_id
     *
     * @return the value of tbl_api_info.app_id
     *
     *
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_api_info.app_id
     *
     * @param appId
     *            the value for tbl_api_info.app_id
     *
     *
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_api_info.group_id
     *
     * @return the value of tbl_api_info.group_id
     *
     *
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_api_info.group_id
     *
     * @param groupId
     *            the value for tbl_api_info.group_id
     *
     *
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_api_info.rpc_type
     *
     * @return the value of tbl_api_info.rpc_type
     *
     *
     */
    public String getRpcType() {
        return rpcType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_api_info.rpc_type
     *
     * @param rpcType
     *            the value for tbl_api_info.rpc_type
     *
     *
     */
    public void setRpcType(String rpcType) {
        this.rpcType = rpcType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_api_info.version
     *
     * @return the value of tbl_api_info.version
     *
     *
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_api_info.version
     *
     * @param version
     *            the value for tbl_api_info.version
     *
     *
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_api_info.api_type
     *
     * @return the value of tbl_api_info.api_type
     *
     *
     */
    public String getApiType() {
        return apiType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_api_info.api_type
     *
     * @param apiType
     *            the value for tbl_api_info.api_type
     *
     *
     */
    public void setApiType(String apiType) {
        this.apiType = apiType;
    }

    public String getApiEnabled() {
        return apiEnabled;
    }

    public void setApiEnabled(String apiEnabled) {
        this.apiEnabled = apiEnabled;
    }

    public String getApiHeader() {
        return apiHeader;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_api_info.api_header
     *
     * @param apiHeader
     *            the value for tbl_api_info.api_header
     *
     *
     */
    public void setApiHeader(String apiHeader) {
        this.apiHeader = apiHeader;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_api_info.api_rewrite
     *
     * @return the value of tbl_api_info.api_rewrite
     *
     *
     */
    public String getApiRewrite() {
        return apiRewrite;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_api_info.api_rewrite
     *
     * @param apiRewrite
     *            the value for tbl_api_info.api_rewrite
     *
     *
     */
    public void setApiRewrite(String apiRewrite) {
        this.apiRewrite = apiRewrite;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_api_info.url
     *
     * @return the value of tbl_api_info.url
     *
     *
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_api_info.url
     *
     * @param url
     *            the value for tbl_api_info.url
     *
     *
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_api_info.method_type
     *
     * @return the value of tbl_api_info.method_type
     *
     *
     */
    public String getMethodType() {
        return methodType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_api_info.method_type
     *
     * @param methodType
     *            the value for tbl_api_info.method_type
     *
     *
     */
    public void setMethodType(String methodType) {
        this.methodType = methodType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_api_info.api_req_size
     *
     * @return the value of tbl_api_info.api_req_size
     *
     *
     */
    public String getApiReqSize() {
        return apiReqSize;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_api_info.api_req_size
     *
     * @param apiReqSize
     *            the value for tbl_api_info.api_req_size
     *
     *
     */
    public void setApiReqSize(String apiReqSize) {
        this.apiReqSize = apiReqSize;
    }

    public String getBlacklistEnabled() {
        return blacklistEnabled;
    }

    public void setBlacklistEnabled(String blacklistEnabled) {
        this.blacklistEnabled = blacklistEnabled;
    }

    public String getApiHystrix() {
        return apiHystrix;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_api_info.api_hystrix
     *
     * @param apiHystrix
     *            the value for tbl_api_info.api_hystrix
     *
     *
     */
    public void setApiHystrix(String apiHystrix) {
        this.apiHystrix = apiHystrix;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_api_info.api_request_limit
     *
     * @return the value of tbl_api_info.api_request_limit
     *
     *
     */
    public String getApiRequestLimit() {
        return apiRequestLimit;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_api_info.api_request_limit
     *
     * @param apiRequestLimit
     *            the value for tbl_api_info.api_request_limit
     *
     *
     */
    public void setApiRequestLimit(String apiRequestLimit) {
        this.apiRequestLimit = apiRequestLimit;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_api_info.api_http_route
     *
     * @return the value of tbl_api_info.api_http_route
     *
     *
     */
    public String getApiHttpRoute() {
        return apiHttpRoute;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_api_info.api_http_route
     *
     * @param apiHttpRoute
     *            the value for tbl_api_info.api_http_route
     *
     *
     */
    public void setApiHttpRoute(String apiHttpRoute) {
        this.apiHttpRoute = apiHttpRoute;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_api_info.api_auth
     *
     * @return the value of tbl_api_info.api_auth
     *
     *
     */
    public String getApiAuth() {
        return apiAuth;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_api_info.api_auth
     *
     * @param apiAuth
     *            the value for tbl_api_info.api_auth
     *
     *
     */
    public void setApiAuth(String apiAuth) {
        this.apiAuth = apiAuth;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_api_info.create_user
     *
     * @return the value of tbl_api_info.create_user
     *
     *
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_api_info.create_user
     *
     * @param createUser
     *            the value for tbl_api_info.create_user
     *
     *
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_api_info.create_time
     *
     * @return the value of tbl_api_info.create_time
     *
     *
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_api_info.create_time
     *
     * @param createTime
     *            the value for tbl_api_info.create_time
     *
     *
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_api_info.update_user
     *
     * @return the value of tbl_api_info.update_user
     *
     *
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_api_info.update_user
     *
     * @param updateUser
     *            the value for tbl_api_info.update_user
     *
     *
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_api_info.update_time
     *
     * @return the value of tbl_api_info.update_time
     *
     *
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_api_info.update_time
     *
     * @param updateTime
     *            the value for tbl_api_info.update_time
     *
     *
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_api_info.api_non_httpRoute
     *
     * @return the value of tbl_api_info.api_non_httpRoute
     *
     *
     */
    public String getApiNonHttproute() {
        return apiNonHttproute;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_api_info.api_non_httpRoute
     *
     * @param apiNonHttproute
     *            the value for tbl_api_info.api_non_httpRoute
     *
     *
     */
    public void setApiNonHttproute(String apiNonHttproute) {
        this.apiNonHttproute = apiNonHttproute;
    }

}