/*
 * Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE
 * file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file
 * to You under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the
 * License. You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package org.palading.clivia.dbCore.domain;

import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.Date;

@Entity(name = "tbl_blacklist_info")
public class TblBlacklistInfo {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_blacklist_info.blacklist_id
     *
     *
     */
    @Id
    private String blacklistId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_blacklist_info.blacklist_ip
     *
     *
     */
    private String blacklistIp;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_blacklist_info.state
     *
     *
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_blacklist_info.group_id
     *
     *
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_blacklist_info.create_user
     *
     *
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_blacklist_info.create_time
     *
     *
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_blacklist_info.update_user
     *
     *
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_blacklist_info.update_time
     *
     *
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_blacklist_info.ext1
     *
     *
     */
    private String ext1;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_blacklist_info.blacklist_id
     *
     * @return the value of tbl_blacklist_info.blacklist_id
     *
     *
     */
    public String getBlacklistId() {
        return blacklistId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_blacklist_info.blacklist_id
     *
     * @param blacklistId
     *            the value for tbl_blacklist_info.blacklist_id
     *
     *
     */
    public void setBlacklistId(String blacklistId) {
        this.blacklistId = blacklistId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_blacklist_info.blacklist_ip
     *
     * @return the value of tbl_blacklist_info.blacklist_ip
     *
     *
     */
    public String getBlacklistIp() {
        return blacklistIp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_blacklist_info.blacklist_ip
     *
     * @param blacklistIp
     *            the value for tbl_blacklist_info.blacklist_ip
     *
     *
     */
    public void setBlacklistIp(String blacklistIp) {
        this.blacklistIp = blacklistIp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_blacklist_info.state
     *
     * @return the value of tbl_blacklist_info.state
     *
     *
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_blacklist_info.state
     *
     * @param state
     *            the value for tbl_blacklist_info.state
     *
     *
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_blacklist_info.group_id
     *
     * @return the value of tbl_blacklist_info.group_id
     *
     *
     */
    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_blacklist_info.create_user
     *
     * @return the value of tbl_blacklist_info.create_user
     *
     *
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_blacklist_info.create_user
     *
     * @param createUser
     *            the value for tbl_blacklist_info.create_user
     *
     *
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_blacklist_info.create_time
     *
     * @return the value of tbl_blacklist_info.create_time
     *
     *
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_blacklist_info.create_time
     *
     * @param createTime
     *            the value for tbl_blacklist_info.create_time
     *
     *
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_blacklist_info.update_user
     *
     * @return the value of tbl_blacklist_info.update_user
     *
     *
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_blacklist_info.update_user
     *
     * @param updateUser
     *            the value for tbl_blacklist_info.update_user
     *
     *
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_blacklist_info.update_time
     *
     * @return the value of tbl_blacklist_info.update_time
     *
     *
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_blacklist_info.update_time
     *
     * @param updateTime
     *            the value for tbl_blacklist_info.update_time
     *
     *
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_blacklist_info.ext1
     *
     * @return the value of tbl_blacklist_info.ext1
     *
     *
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_blacklist_info.ext1
     *
     * @param ext1
     *            the value for tbl_blacklist_info.ext1
     *
     *
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
}