/*
 * Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE
 * file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file
 * to You under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the
 * License. You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package org.palading.clivia.dbCore.domain;

import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.Date;

@Entity(name = "tbl_client_security")
public class TblClientSecurity {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_client_security.id
     *
     *
     */
    @Id
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_client_security.client_name
     *
     *
     */
    private String clientName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_client_security.token
     *
     *
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_client_security.state
     *
     *
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_client_security.create_user
     *
     *
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_client_security.create_time
     *
     *
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_client_security.update_user
     *
     *
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_client_security.update_time
     *
     *
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_client_security.client_pwd
     *
     *
     */
    private String clientPwd;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_client_security.id
     *
     * @return the value of tbl_client_security.id
     *
     *
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_client_security.id
     *
     * @param id
     *            the value for tbl_client_security.id
     *
     *
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_client_security.client_name
     *
     * @return the value of tbl_client_security.client_name
     *
     *
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_client_security.client_name
     *
     * @param clientName
     *            the value for tbl_client_security.client_name
     *
     *
     */
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_client_security.token
     *
     * @return the value of tbl_client_security.token
     *
     *
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_client_security.token
     *
     * @param token
     *            the value for tbl_client_security.token
     *
     *
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_client_security.state
     *
     * @return the value of tbl_client_security.state
     *
     *
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_client_security.state
     *
     * @param state
     *            the value for tbl_client_security.state
     *
     *
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_client_security.create_user
     *
     * @return the value of tbl_client_security.create_user
     *
     *
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_client_security.create_user
     *
     * @param createUser
     *            the value for tbl_client_security.create_user
     *
     *
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_client_security.create_time
     *
     * @return the value of tbl_client_security.create_time
     *
     *
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_client_security.create_time
     *
     * @param createTime
     *            the value for tbl_client_security.create_time
     *
     *
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_client_security.update_user
     *
     * @return the value of tbl_client_security.update_user
     *
     *
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_client_security.update_user
     *
     * @param updateUser
     *            the value for tbl_client_security.update_user
     *
     *
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_client_security.update_time
     *
     * @return the value of tbl_client_security.update_time
     *
     *
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_client_security.update_time
     *
     * @param updateTime
     *            the value for tbl_client_security.update_time
     *
     *
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_client_security.client_pwd
     *
     * @return the value of tbl_client_security.client_pwd
     *
     *
     */
    public String getClientPwd() {
        return clientPwd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_client_security.client_pwd
     *
     * @param clientPwd
     *            the value for tbl_client_security.client_pwd
     *
     *
     */
    public void setClientPwd(String clientPwd) {
        this.clientPwd = clientPwd;
    }
}